---
- name: Install 389DS with zypper
  zypper:
    name: "{{ dirsrv_product }}"
    state: latest
    update_cache: no

- name: Check 389DS package version with rpm
  command:
    cmd: "rpm -q --qf '%{version}' {{ dirsrv_product }}"
  register: dirsrv_package_details
  check_mode: false

- name: Check 389DS package version
  set_fact:
    dirsrv_package_version: "{{ dirsrv_package_details.stdout }}"
